Task 1_3
DaniilSukhanov/AS3_1 pull request #1
Opened 2024-10-17 23:28 UTC by DaniilSukhanov

2024-10-18 10:34 UTC, SolarHaddock46 requested changes
начало хорошее, но много над чем нужно работать. внимательно смотри комменты. после изменений закидывай еще один пулл реквест так же, как закинул этот

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/AppColor.swift
> +    static var backgroudView: UIColor {
опечатка

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/AppColor.swift
> +    static var text: UIColor {
переименовать хотя бы в textColor

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +        static let offestUpTitleLabel: CGFloat = 10
offset?

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +        static let verticalPaddingScrollView: CGFloat = 25
такие переменные лучше называть в формате scrollViewVerticalPadding
это касается почти всех переменных далее по структуре

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +    private lazy var scrollView: UIScrollView = {
можно без lazy и кложуры, если нет дополнительных настроек

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +    private struct Constant {
лучше назвать Constants и сделать енумом

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +    private lazy var toggleButtonColoring: UIStackView = {
переименовать в coloringToggleButton, toggleButtonColoring наводит на мысль, что эта кнопка триггерит закраску кнопки, а не текста

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +    private lazy var placeholderTextEditor: UILabel = {
переименовать в textEditorPlaceholder, placeholderTextEditor - название для редактора текста плейсхолдера, а не плейсхолдера редактора текста

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +        let placeholderTextEditor = UILabel()
внутри кложур можно переменные результата называть покороче

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +        labelToggleButtonColoring.text = "is red text"
лейблы для юзера стоит писать более понятными, например, "Make text red"

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +    private lazy var sliderSizeFont: UISlider = {
fontSizeSlider

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +        let sliderSizeFont = UISlider()
короче

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +        let labelToggleButtonColoring = UILabel()
никаких длинных названий переменных в кложурах. spacer и stackView назвал нормально, все остальное в кложурах называй так же коротко, сойдет просто button, label итд

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +    private lazy var textEditor: UITextView = {
это лучше назвать textField или textView, если уж решил использовать его

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +        submitButton.backgroundColor = .blue
комбинация цветов на кнопке мягко говоря получилась вырвиглазная, для кнопки с черным текстом нужны цвета поярче или вообще никаких цветов, а просто заливка границы

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +private extension ViewController {
шикарный мув, мне нравится

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +        setupLayoutsScrollView()
эти функции можно назвать без Layouts, ты же уже уточнил это в функции, из которой они вызываются
лучше просто setupScrollView, setupMainStackView итд

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +            scrollView.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor),
при установке top и leading можно не устанавливать bottom и trailing. лучше установить width и height, равные константам

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +            mainStackView.bottomAnchor.constraint(equalTo: scrollView.bottomAnchor),
можно упростить, см коммент далее

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +            submitButton.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: -Constant.botomPaddingSubmitButton),
упростить, минус константу убрать

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +            placeholderTextEditor.bottomAnchor.constraint(lessThanOrEqualTo: textEditor.safeAreaLayoutGuide.bottomAnchor, constant: -Constant.verticalPaddingPlaceholderTextEditor),
тоже упростить и убрать минус константу

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +            logger.warning("Text is nil!")
варнинг вместо логгера лучше выдавать через алерт юзеру

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +            logger.info("Text: \(text)")
это лучше выдать в алерт, со стороны юзера кажется, что кнопка не делает ничего

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +        NSLayoutConstraint.activate([
добавить паддинги между констрейнтами скроллвью и стеквью, без них элементы стеквью обрезаются

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +        placeholderTextEditor.isHidden = !textEditor.text.isEmpty
чтобы не делать такие костыли, можно вместо textView использовать textField, которому можно задать плейсхолдер

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +    @objc func removeFocuseTextEditor(_ sender: UITapGestureRecognizer) {
опечатка

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/ViewController.swift
> +        title = "Editor"
title можно не писать, если нет навбара

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/SceneDelegate.swift
> +        window?.rootViewController = UINavigationController(rootViewController: ViewController())
для приложения с одним вьюконтроллером не обязательно создавать навигейшнконтроллер, достатояно указать просто window?.rootViewController = ViewController()

2024-10-18 10:34 UTC, SolarHaddock46 commented on AutmnSchoolHM1_3/AppColor.swift
> +struct AppColor {
сделать енумом

2024-10-18 10:35 UTC, SolarHaddock46 commented
забыл упомянуть в ревью - минимальный размер текста (он же размер по умолчанию) должен по высоте совпадать с минимальной высотой твоего текствью/текстфилда

2024-10-23 18:19 UTC, Wtclrsnd reviewed
неплохо сыграно, как говорится

2024-10-23 18:19 UTC, Wtclrsnd commented on AutmnSchoolHM1_3/ViewController.swift
> +        label.font = .systemFont(ofSize: 14)
если уж брать по высшему разряду, то шрифты тоже можно вынести как ты вынес AppColor

2024-10-23 18:19 UTC, Wtclrsnd commented on AutmnSchoolHM1_3/ViewController.swift
> +        let stackView = UIStackView(arrangedSubviews: [label, spacer, toggleButtonColoring])
спейсер не нужен ведь есть `setCustomSpacing(_:after:)`

2024-10-23 18:19 UTC, Wtclrsnd commented on AutmnSchoolHM1_3/ViewController.swift
> +            placeholder.leadingAnchor.constraint(equalTo: textView.safeAreaLayoutGuide.leadingAnchor, constant: Constant.leadingPaddingPlaceholderTextEditor),
у горизонтальных сторон сейф ареа совпадает с анкорами так что можно ее не тащить

2024-10-23 18:19 UTC, Wtclrsnd commented on AutmnSchoolHM1_3/ViewController.swift
> +            logger.warning("Text is nil!")
да можно но избыточно в рамках этого дз

2024-11-23 13:49 UTC, merged